### ISSUE TITLE
Issue with '=' in album name still persists...

### ISSUE THREAD

**Issue by LyingJay** [jojo2357/Music-Discord-Rich-Presence#13]
I have attached screenshots of the discord application, the .dat file, the DRP window and the song details shown in groove for the relevant song.
By 'remove = from the keyset' I assume it means to just write in the album name as if the = was not there. Am I misinterpreting the instruction? The album artworks for all my other songs work perfectly fine.

What DRP shows (no purple confirmation text ): )
![image](https://user-images.githubusercontent.com/78644149/109419533-079ae300-7a22-11eb-8eea-3528cedc1d42.png)

The image uploaded to Discord Application Assets:
![image](https://user-images.githubusercontent.com/78644149/109419549-20a39400-7a22-11eb-98d9-6b54d5f0d5e6.png)

The album in Groove:
![image](https://user-images.githubusercontent.com/78644149/109419566-3a44db80-7a22-11eb-8ee5-d9b4ac3c2785.png)

What I have put in the .dat file:
![image](https://user-images.githubusercontent.com/78644149/109419642-93147400-7a22-11eb-9b24-33d75baed34a.png)

**Comment by jojo2357** [comment]
I believe this was fixed in 1.3.1 so try that first. And yes, that is what i mean is to just remove the `=` from the album title. Is there a better way i could word it that might be less confusing?

**Comment by LyingJay** [comment]
Ok, I facepalmed when I realised I was in 1.3.0.
However, even after using 1.3.1, this happened:
![image](https://user-images.githubusercontent.com/78644149/109499268-c15c8700-7ae8-11eb-91f0-0dd0a0353e75.png)
All the information shown by the images from the previous post is still the same.

Also, when I link DRP with Groove, or try to use Launch DRP Hidden, this happens:
![image](https://user-images.githubusercontent.com/78644149/109499559-2ca65900-7ae9-11eb-9201-98f3467b45e5.png)

And just in case, but I don't think this matters, this dialog pops up when I try to run DRP Hidden from the shortcut:
![image](https://user-images.githubusercontent.com/78644149/109499484-126c7b00-7ae9-11eb-8eec-b71b36d82bb9.png)
I click the open prompt and it takes me to the previous image.
I have already attempted unlinking, locating and relinking.

About the instructions for dealing with albums with equal signs, it is perfectly clear. I just started questioning whether I was interpreting it wrong when it wasn't working.

**Comment by jojo2357** [comment]
- The warning prompt is standard since I don't have the resources to get a verified windows signature.
- I see you downloaded the release zip so good on you, but try cloning the repo instead because that will give more background stuff (that I may need to start including in future releases i suppose)
- Im curious about the error since it hasn't been reported yet im wondering if there was a special set of circumstances to cause it
- I'm baffled by the vbscript not working right. If it worked before and doesnt work now then that is kinda beyond me. if needed i can offer some debug tips but in the meantime i would use the bat instead because that is tried and true. if the bat doesnt work then theres something else going on

**Comment by jojo2357** [comment]
I downloaded my own release and it worked from there no problem. Apart from deleting and reinstalling the project I need a way to replicate the issue, I'm sorry. Thank you for the good documentation of the issue tho, its just hard to fix a problem I can't make on my own computer :/

**Comment by LyingJay** [comment]
That’s unfortunate. Thanks for your help, anyway! It’s probably something wrong on my end, so I’ll keep trying to fix it. Either way, DRP is still a great project, so continue developing! I’ll let you know if I find a solution/fix. I’ll also try cloning the repo instead of downloading.

**Comment by jojo2357** [comment]
aw thanks that means a lot 😊 I have a lot of other projects going on but Ill be sure to keep maintaining and improving this

**Comment by Smaltin** [comment]
Just wondering, have you done a full deletion of the program and redownloaded the release in full, or are you replacing just certain files? Some things may be lingering and causing issues.

**Comment by LyingJay** [comment]
Yep. What I do when I download is delete the previous version (the folder that has the version number and release in the folder name), keeping the .dat file. Then I place the new version where the old version used to be, and insert the .dat file in the right place.

**Comment by jojo2357** [comment]
could you perchance send the mp3 with the = so i can test if it works for me?

**Comment by LyingJay** [comment]
Sure, but I can’t send it right now so I’ll send it here within the next 12 hours

**Comment by jojo2357** [comment]
thats cool, whenever possible

**Comment by Smaltin** [comment]
I was able to reproduce the issue, I'll work with @jojo2357 to fix it.

**Comment by jojo2357** [comment]
See 1.3.2 and close when you confirm the issue has been resolved @LyingJay

**Comment by LyingJay** [comment]
The issue has been resolved. But maybe change the wording of the instructions a little to make it clear which '=' should become '==', as at first, I replaced the = in the album title, then realised that I was meant to replace the other = sign.

**Comment by jojo2357** [comment]
Done.
